mmdb
MinlyInc/minly-backend-internship-2024 pull request #9
Opened 2024-07-24 11:54 UTC by Mariam22-hub

2024-07-30 21:09 UTC, marwan-a requested changes

2024-07-30 21:09 UTC, marwan-a commented on src/movies/movies.service.ts
> +      console.log(page, limit, sort);
Log statement is not informative

2024-07-30 21:09 UTC, marwan-a commented on src/movies/movies.service.ts
> +      }
If you always use query.andWhere instead of query.where you'll avoid having to check if there was another where condition

2024-07-30 21:09 UTC, marwan-a commented on src/entities/Movie/dto/pagination.dto.ts
> +export class PaginationQueryDto {
This class could be in somewhere generic

2024-07-30 21:09 UTC, marwan-a commented on src/movies/movies.service.ts
> +    try {
The try catch needs to be beneficial either by logging some information related to the error and its params or perhaps doing a different action, but as it stands it's not really adding much

2024-07-30 21:09 UTC, marwan-a commented on src/movies/movies.service.ts
> +  async findSelectedMovie(uuid: UUID): Promise<{ movie: MovieDto }> {
Why not just promise `MovieDto` instead of an object containing an attribute movie

2024-07-30 21:09 UTC, marwan-a commented on src/movies/movies.service.ts
> +      director: director ? `${director.first_name} ${director.last_name}` : null,
You could use a virtual column fullName in the director entity which does this first + last name concatenation.

2024-07-30 21:09 UTC, marwan-a commented on src/movies/movies.service.ts
> +        uuid: ma.actor.uuid
Perhaps you could have a dto for this

2024-07-31 08:49 UTC, Mariam22-hub commented on .eslintrc.js
> +    "@typescript-eslint/prefer-const": "off"
No reason, just a personal preference with linting. I can revert it

2025-04-29 13:02 UTC, closed without merging